/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.structure.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.structure.ui.internal.StructureActivator;

public class StructureUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StructureActivator.getInstance().getInjector("org.xtext.example.structure.Structure");
	}

}
