/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.structure


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StructureStandaloneSetup extends StructureStandaloneSetupGenerated {

	def static void doSetup() {
		new StructureStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
