/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.structure.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.structure.ide.contentassist.antlr.internal.InternalStructureParser;
import org.xtext.example.structure.services.StructureGrammarAccess;

public class StructureParser extends AbstractContentAssistParser {

	@Inject
	private StructureGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalStructureParser createParser() {
		InternalStructureParser result = new InternalStructureParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getExtensionAccess().getAlternatives(), "rule__Extension__Alternatives");
					put(grammarAccess.getRaizAccess().getGroup(), "rule__Raiz__Group__0");
					put(grammarAccess.getCarpetaAccess().getGroup(), "rule__Carpeta__Group__0");
					put(grammarAccess.getCarpetaAccess().getGroup_4(), "rule__Carpeta__Group_4__0");
					put(grammarAccess.getCarpetaAccess().getGroup_6(), "rule__Carpeta__Group_6__0");
					put(grammarAccess.getContentAccess().getGroup(), "rule__Content__Group__0");
					put(grammarAccess.getRaizAccess().getNameAssignment_1(), "rule__Raiz__NameAssignment_1");
					put(grammarAccess.getRaizAccess().getCarpetasAssignment_3(), "rule__Raiz__CarpetasAssignment_3");
					put(grammarAccess.getRaizAccess().getContentsAssignment_4(), "rule__Raiz__ContentsAssignment_4");
					put(grammarAccess.getCarpetaAccess().getPathAssignment_1(), "rule__Carpeta__PathAssignment_1");
					put(grammarAccess.getCarpetaAccess().getNameAssignment_2(), "rule__Carpeta__NameAssignment_2");
					put(grammarAccess.getCarpetaAccess().getChildsAssignment_4_1(), "rule__Carpeta__ChildsAssignment_4_1");
					put(grammarAccess.getCarpetaAccess().getFilesAssignment_6_1(), "rule__Carpeta__FilesAssignment_6_1");
					put(grammarAccess.getContentAccess().getNameAssignment_1(), "rule__Content__NameAssignment_1");
					put(grammarAccess.getContentAccess().getExtAssignment_2(), "rule__Content__ExtAssignment_2");
					put(grammarAccess.getContentAccess().getTextAssignment_4(), "rule__Content__TextAssignment_4");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public StructureGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StructureGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
