/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.structure;

import org.xtext.example.structure.AbstractStructureRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class StructureRuntimeModule extends AbstractStructureRuntimeModule {
}
