/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.structure.ide;

import org.xtext.example.structure.ide.AbstractStructureIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class StructureIdeModule extends AbstractStructureIdeModule {
}
