/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.structure.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.structure.ui.AbstractStructureUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class StructureUiModule extends AbstractStructureUiModule {
  public StructureUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
