/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.structure.validation;

import org.xtext.example.structure.validation.AbstractStructureValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class StructureValidator extends AbstractStructureValidator {
}
