/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.structure.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.structure.parser.antlr.internal.InternalStructureParser;
import org.xtext.example.structure.services.StructureGrammarAccess;

public class StructureParser extends AbstractAntlrParser {

	@Inject
	private StructureGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalStructureParser createParser(XtextTokenStream stream) {
		return new InternalStructureParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Raiz";
	}

	public StructureGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StructureGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
