/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.structure.structure;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Carpeta</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.structure.structure.Carpeta#getPath <em>Path</em>}</li>
 *   <li>{@link org.xtext.example.structure.structure.Carpeta#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.structure.structure.Carpeta#getChilds <em>Childs</em>}</li>
 *   <li>{@link org.xtext.example.structure.structure.Carpeta#getFiles <em>Files</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.structure.structure.StructurePackage#getCarpeta()
 * @model
 * @generated
 */
public interface Carpeta extends EObject
{
  /**
   * Returns the value of the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Path</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' attribute.
   * @see #setPath(String)
   * @see org.xtext.example.structure.structure.StructurePackage#getCarpeta_Path()
   * @model
   * @generated
   */
  String getPath();

  /**
   * Sets the value of the '{@link org.xtext.example.structure.structure.Carpeta#getPath <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' attribute.
   * @see #getPath()
   * @generated
   */
  void setPath(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.structure.structure.StructurePackage#getCarpeta_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.structure.structure.Carpeta#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Childs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.structure.structure.Carpeta}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Childs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Childs</em>' containment reference list.
   * @see org.xtext.example.structure.structure.StructurePackage#getCarpeta_Childs()
   * @model containment="true"
   * @generated
   */
  EList<Carpeta> getChilds();

  /**
   * Returns the value of the '<em><b>Files</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.structure.structure.Content}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Files</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Files</em>' reference list.
   * @see org.xtext.example.structure.structure.StructurePackage#getCarpeta_Files()
   * @model
   * @generated
   */
  EList<Content> getFiles();

} // Carpeta
