/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.structure.structure;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.structure.structure.StructureFactory
 * @model kind="package"
 * @generated
 */
public interface StructurePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "structure";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/structure/Structure";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "structure";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  StructurePackage eINSTANCE = org.xtext.example.structure.structure.impl.StructurePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.structure.structure.impl.RaizImpl <em>Raiz</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.structure.structure.impl.RaizImpl
   * @see org.xtext.example.structure.structure.impl.StructurePackageImpl#getRaiz()
   * @generated
   */
  int RAIZ = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RAIZ__NAME = 0;

  /**
   * The feature id for the '<em><b>Carpetas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RAIZ__CARPETAS = 1;

  /**
   * The feature id for the '<em><b>Contents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RAIZ__CONTENTS = 2;

  /**
   * The number of structural features of the '<em>Raiz</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RAIZ_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.structure.structure.impl.CarpetaImpl <em>Carpeta</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.structure.structure.impl.CarpetaImpl
   * @see org.xtext.example.structure.structure.impl.StructurePackageImpl#getCarpeta()
   * @generated
   */
  int CARPETA = 1;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARPETA__PATH = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARPETA__NAME = 1;

  /**
   * The feature id for the '<em><b>Childs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARPETA__CHILDS = 2;

  /**
   * The feature id for the '<em><b>Files</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARPETA__FILES = 3;

  /**
   * The number of structural features of the '<em>Carpeta</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARPETA_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.structure.structure.impl.ContentImpl <em>Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.structure.structure.impl.ContentImpl
   * @see org.xtext.example.structure.structure.impl.StructurePackageImpl#getContent()
   * @generated
   */
  int CONTENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Ext</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__EXT = 1;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__TEXT = 2;

  /**
   * The number of structural features of the '<em>Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.example.structure.structure.Raiz <em>Raiz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Raiz</em>'.
   * @see org.xtext.example.structure.structure.Raiz
   * @generated
   */
  EClass getRaiz();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.structure.structure.Raiz#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.structure.structure.Raiz#getName()
   * @see #getRaiz()
   * @generated
   */
  EAttribute getRaiz_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.structure.structure.Raiz#getCarpetas <em>Carpetas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Carpetas</em>'.
   * @see org.xtext.example.structure.structure.Raiz#getCarpetas()
   * @see #getRaiz()
   * @generated
   */
  EReference getRaiz_Carpetas();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.structure.structure.Raiz#getContents <em>Contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contents</em>'.
   * @see org.xtext.example.structure.structure.Raiz#getContents()
   * @see #getRaiz()
   * @generated
   */
  EReference getRaiz_Contents();

  /**
   * Returns the meta object for class '{@link org.xtext.example.structure.structure.Carpeta <em>Carpeta</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Carpeta</em>'.
   * @see org.xtext.example.structure.structure.Carpeta
   * @generated
   */
  EClass getCarpeta();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.structure.structure.Carpeta#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.structure.structure.Carpeta#getPath()
   * @see #getCarpeta()
   * @generated
   */
  EAttribute getCarpeta_Path();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.structure.structure.Carpeta#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.structure.structure.Carpeta#getName()
   * @see #getCarpeta()
   * @generated
   */
  EAttribute getCarpeta_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.structure.structure.Carpeta#getChilds <em>Childs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Childs</em>'.
   * @see org.xtext.example.structure.structure.Carpeta#getChilds()
   * @see #getCarpeta()
   * @generated
   */
  EReference getCarpeta_Childs();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.structure.structure.Carpeta#getFiles <em>Files</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Files</em>'.
   * @see org.xtext.example.structure.structure.Carpeta#getFiles()
   * @see #getCarpeta()
   * @generated
   */
  EReference getCarpeta_Files();

  /**
   * Returns the meta object for class '{@link org.xtext.example.structure.structure.Content <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Content</em>'.
   * @see org.xtext.example.structure.structure.Content
   * @generated
   */
  EClass getContent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.structure.structure.Content#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.structure.structure.Content#getName()
   * @see #getContent()
   * @generated
   */
  EAttribute getContent_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.structure.structure.Content#getExt <em>Ext</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ext</em>'.
   * @see org.xtext.example.structure.structure.Content#getExt()
   * @see #getContent()
   * @generated
   */
  EAttribute getContent_Ext();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.structure.structure.Content#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.structure.structure.Content#getText()
   * @see #getContent()
   * @generated
   */
  EAttribute getContent_Text();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  StructureFactory getStructureFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.structure.structure.impl.RaizImpl <em>Raiz</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.structure.structure.impl.RaizImpl
     * @see org.xtext.example.structure.structure.impl.StructurePackageImpl#getRaiz()
     * @generated
     */
    EClass RAIZ = eINSTANCE.getRaiz();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RAIZ__NAME = eINSTANCE.getRaiz_Name();

    /**
     * The meta object literal for the '<em><b>Carpetas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RAIZ__CARPETAS = eINSTANCE.getRaiz_Carpetas();

    /**
     * The meta object literal for the '<em><b>Contents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RAIZ__CONTENTS = eINSTANCE.getRaiz_Contents();

    /**
     * The meta object literal for the '{@link org.xtext.example.structure.structure.impl.CarpetaImpl <em>Carpeta</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.structure.structure.impl.CarpetaImpl
     * @see org.xtext.example.structure.structure.impl.StructurePackageImpl#getCarpeta()
     * @generated
     */
    EClass CARPETA = eINSTANCE.getCarpeta();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARPETA__PATH = eINSTANCE.getCarpeta_Path();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARPETA__NAME = eINSTANCE.getCarpeta_Name();

    /**
     * The meta object literal for the '<em><b>Childs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARPETA__CHILDS = eINSTANCE.getCarpeta_Childs();

    /**
     * The meta object literal for the '<em><b>Files</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARPETA__FILES = eINSTANCE.getCarpeta_Files();

    /**
     * The meta object literal for the '{@link org.xtext.example.structure.structure.impl.ContentImpl <em>Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.structure.structure.impl.ContentImpl
     * @see org.xtext.example.structure.structure.impl.StructurePackageImpl#getContent()
     * @generated
     */
    EClass CONTENT = eINSTANCE.getContent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENT__NAME = eINSTANCE.getContent_Name();

    /**
     * The meta object literal for the '<em><b>Ext</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENT__EXT = eINSTANCE.getContent_Ext();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENT__TEXT = eINSTANCE.getContent_Text();

  }

} //StructurePackage
